<?php
    date_default_timezone_set('UTC');
    ini_set('session.cookie_httponly', 1);
    if (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on') {
        ini_set('session.cookie_secure', 1);
    }
    ini_set('session.cookie_samesite', 'Lax');
    session_start();
    require_once __DIR__ . '/vendor/autoload.php';
    $dotenv = Dotenv\Dotenv::createImmutable(__DIR__);
    $dotenv->load();
    require_once __DIR__ . '/app/helpers/helpers.php';
    require_once __DIR__ . '/config.php';
    require_once __DIR__ . '/app/core/Database.php';
    require_once __DIR__ . '/app/core/Controller.php';
    require_once __DIR__ . '/app/core/Router.php';
    spl_autoload_register(function ($class) {
        $paths = ['app/controllers/', 'app/models/', 'app/core/', 'app/services/'];
        foreach ($paths as $path) {
            $file = __DIR__ . '/' . $path . $class . '.php';
            if (file_exists($file)) {
                require_once $file;
                return;
            }
        }
    });
    // TODO(A5, deferred): replace with real login/session issuance. company_id must match a
    // real row in `companies` -- getCompId() now reads this key directly (previously it read
    // $_SESSION['comp_id'], which was never set anywhere, so every request silently fell back to
    // a hardcoded comp_id=1 regardless of this array; fixed alongside the Phase A security pass).
    $_SESSION['user'] = [
        'employee_id' => 2,
        'company_id'  => 1,
        'role'        => 'admin'
    ];
    ensure_login();
    $router = new Router();
    $router->get('auth', 'AuthController@permission'); 
    $router->get('/', 'DashboardController@index'); 
    $router->get('dashboard', 'DashboardController@index');
    $router->get('employees', 'EmployeeController@index');
    $router->get('/payroll-process', 'PayrollController@index');
    $router->get('/payroll-process/{id}', 'PayrollController@detail');
    $router->post('api/payroll-run.options', 'PayrollController@options');
    $router->get('/payroll-approval', 'PayrollController@approvalQueue');
    $router->get('api/payroll-run.list', 'PayrollController@list');
    $router->get('api/payroll-run.get', 'PayrollController@get');
    $router->post('api/payroll-run.save', 'PayrollController@save');
    $router->post('api/payroll-run.delete', 'PayrollController@delete');
    $router->post('api/payroll-run.recalculate', 'PayrollController@recalculate');
    $router->post('api/payroll-run.submit', 'PayrollController@submit');
    $router->post('api/payroll-run.revert', 'PayrollController@revert');
    $router->post('api/payroll-run.approve', 'PayrollController@approve');
    $router->post('api/payroll-run.reject', 'PayrollController@reject');
    $router->post('api/payroll-run.revise-after-reject', 'PayrollController@reviseAfterReject');
    $router->post('api/payroll-run.mark-paid', 'PayrollController@markPaid');
    $router->post('api/payroll-run.lock', 'PayrollController@lock');
    $router->get('setup/company-profile', 'CompanyProfileController@index');
    $router->get('setup/payroll-configuration', 'PayrollConfigurationController@index');
    $router->post('api/payroll-cycle.options', 'PayrollConfigurationController@cycleOptions');
    $router->post('api/bank-file-format.options', 'PayrollConfigurationController@bankFileFormatOptions');
    $router->get('api/payroll-cycle.list', 'PayrollConfigurationController@cycleList');
    $router->get('api/payroll-cycle.get', 'PayrollConfigurationController@cycleGet');
    $router->post('api/payroll-cycle.save', 'PayrollConfigurationController@cycleSave');
    $router->post('api/payroll-cycle.delete', 'PayrollConfigurationController@cycleDelete');
    $router->get('api/attendance-bonus.list', 'PayrollConfigurationController@attendanceBonusList');
    $router->get('api/attendance-bonus.get', 'PayrollConfigurationController@attendanceBonusGet');
    $router->post('api/attendance-bonus.save', 'PayrollConfigurationController@attendanceBonusSave');
    $router->post('api/attendance-bonus.delete', 'PayrollConfigurationController@attendanceBonusDelete');
    $router->post('api/attendance-bonus.scheme-options', 'PayrollConfigurationController@bonusSchemeOptions');
    $router->get('api/attendance-bonus.ledger.list', 'PayrollConfigurationController@bonusLedgerList');
    $router->get('api/attendance-bonus.ledger.get', 'PayrollConfigurationController@bonusLedgerGet');
    $router->post('api/attendance-bonus.ledger.save', 'PayrollConfigurationController@bonusLedgerSave');
    $router->post('api/attendance-bonus.ledger.lock', 'PayrollConfigurationController@bonusLedgerLock');
    $router->post('api/attendance-bonus.ledger.delete', 'PayrollConfigurationController@bonusLedgerDelete');
    $router->post('api/ped-type.source-event-options', 'PayrollConfigurationController@pedSourceEventOptions');
    $router->post('api/ped-type.list', 'PayrollConfigurationController@pedTypeList');
    $router->get('api/ped-type.get', 'PayrollConfigurationController@pedTypeGet');
    $router->post('api/ped-type.save', 'PayrollConfigurationController@pedTypeSave');
    $router->post('api/ped-type.delete', 'PayrollConfigurationController@pedTypeDelete');
    $router->get('setup/tax-statutory', 'TaxStatutoryController@index');
    $router->get('api/statutory-item.list', 'TaxStatutoryController@itemList');
    $router->get('api/statutory-item.get', 'TaxStatutoryController@itemGet');
    $router->post('api/statutory-item.save', 'TaxStatutoryController@itemSave');
    $router->post('api/statutory-item.delete', 'TaxStatutoryController@itemDelete');
    $router->get('api/statutory-item.rate-history.list', 'TaxStatutoryController@rateHistoryList');
    $router->get('api/statutory-item.rate-history.get', 'TaxStatutoryController@rateHistoryGet');
    $router->post('api/statutory-item.rate-history.save', 'TaxStatutoryController@rateHistorySave');
    $router->post('api/statutory-item.rate-history.delete', 'TaxStatutoryController@rateHistoryDelete');
    $router->get('api/company-statutory-setting.list', 'TaxStatutoryController@companySettingList');
    $router->get('api/company-statutory-setting.get', 'TaxStatutoryController@companySettingGet');
    $router->post('api/company-statutory-setting.save', 'TaxStatutoryController@companySettingSave');
    $router->post('api/company-statutory-setting.reset', 'TaxStatutoryController@companySettingReset');
    $router->get('setup/document-approval', 'DocumentApprovalController@index');
    $router->post('api/approval-workflow.document-type-options', 'ApprovalWorkflowController@documentTypeOptions');
    $router->get('api/approval-workflow.list', 'ApprovalWorkflowController@workflowList');
    $router->get('api/approval-workflow.get', 'ApprovalWorkflowController@workflowGet');
    $router->post('api/approval-workflow.save', 'ApprovalWorkflowController@workflowSave');
    $router->post('api/approval-workflow.delete', 'ApprovalWorkflowController@workflowDelete');
    $router->post('api/approval-workflow.duplicate', 'ApprovalWorkflowController@workflowDuplicate');
    $router->post('api/approval-workflow.toggle-status', 'ApprovalWorkflowController@workflowToggleStatus');
    $router->post('api/approval-request.create', 'ApprovalWorkflowController@requestCreate');
    $router->post('api/approval-request.act', 'ApprovalWorkflowController@requestAct');
    $router->get('api/approval-request.get', 'ApprovalWorkflowController@requestGet');
    $router->get('api/approval-request.list', 'ApprovalWorkflowController@requestList');
    $router->get('api/approval-request.logs', 'ApprovalWorkflowController@requestLogs');
    $router->get('setup/notification', 'NotificationController@index');
    $router->get('setup-rules', 'SetupRulesController@index');
    $router->get('api/shift.list', 'SetupRulesController@shiftList');
    $router->get('api/shift.get', 'SetupRulesController@shiftGet');
    $router->post('api/shift.save', 'SetupRulesController@shiftSave');
    $router->post('api/shift.delete', 'SetupRulesController@shiftDelete');
    $router->post('api/shift.toggle-status', 'SetupRulesController@shiftToggleStatus');
    $router->get('api/shift.assigned-employees', 'SetupRulesController@shiftAssignedEmployees');
    $router->post('api/shift.assign-employees', 'SetupRulesController@shiftAssignEmployees');
    $router->get('api/work-location.list', 'SetupRulesController@workLocationList');
    $router->get('api/work-location.get', 'SetupRulesController@workLocationGet');
    $router->post('api/work-location.save', 'SetupRulesController@workLocationSave');
    $router->post('api/work-location.delete', 'SetupRulesController@workLocationDelete');
    $router->post('api/work-location.toggle-status', 'SetupRulesController@workLocationToggleStatus');
    $router->post('api/work-location.options', 'SetupRulesController@workLocationOptions');
    $router->post('api/leave-category.options', 'SetupRulesController@leaveCategoryOptions');
    $router->get('api/leave-type.list', 'SetupRulesController@leaveTypeList');
    $router->get('api/leave-type.get', 'SetupRulesController@leaveTypeGet');
    $router->post('api/leave-type.save', 'SetupRulesController@leaveTypeSave');
    $router->post('api/leave-type.delete', 'SetupRulesController@leaveTypeDelete');
    $router->post('api/leave-type.toggle-status', 'SetupRulesController@leaveTypeToggleStatus');
    $router->get('api/permission-matrix.get', 'PermissionController@matrix');
    $router->post('api/permission-matrix.save', 'PermissionController@save');
    $router->post('api/payslip-template.field-options', 'PayslipTemplateController@fieldTypeOptions');
    $router->get('api/payslip-template.list', 'PayslipTemplateController@list');
    $router->get('api/payslip-template.get', 'PayslipTemplateController@get');
    $router->post('api/payslip-template.save', 'PayslipTemplateController@save');
    $router->post('api/payslip-template.delete', 'PayslipTemplateController@delete');
    $router->post('api/payslip-template.toggle-status', 'PayslipTemplateController@toggleStatus');
    $router->post('api/payslip-template.upload-logo', 'PayslipTemplateController@uploadLogo');
    $router->post('api/payslip-template.preview', 'PayslipTemplateController@preview');
    $router->post('api/payslip-distribution.channel-options', 'PayslipDistributionController@channelOptions');
    $router->get('api/payslip-distribution.settings-get', 'PayslipDistributionController@settingsGet');
    $router->post('api/payslip-distribution.settings-save', 'PayslipDistributionController@settingsSave');
    $router->get('api/payslip-request.list', 'PayslipRequestController@list');
    $router->get('api/payslip-request.get', 'PayslipRequestController@get');
    $router->post('api/payslip-request.run-options', 'PayslipRequestController@runOptions');
    $router->post('api/payslip-request.employee-options', 'PayslipRequestController@employeeOptions');
    $router->post('api/payslip-request.create', 'PayslipRequestController@create');
    $router->get('api/payslip-delivery-log.list', 'PayslipDeliveryLogController@list');
    $router->post('api/payslip-delivery-log.resend', 'PayslipDeliveryLogController@resend');
    $router->get('manual-entry', 'ManualEntryController@index');
    $router->get('api/manual-attendance.list', 'ManualEntryController@attendanceList');
    $router->get('api/manual-attendance.get', 'ManualEntryController@attendanceGet');
    $router->post('api/manual-attendance.save', 'ManualEntryController@attendanceSave');
    $router->post('api/manual-attendance.delete', 'ManualEntryController@attendanceDelete');
    $router->get('api/manual-leave.list', 'ManualEntryController@leaveList');
    $router->get('api/manual-leave.get', 'ManualEntryController@leaveGet');
    $router->post('api/manual-leave.save', 'ManualEntryController@leaveSave');
    $router->post('api/manual-leave.delete', 'ManualEntryController@leaveDelete');
    $router->get('api/manual-overtime.list', 'ManualEntryController@overtimeList');
    $router->get('api/manual-overtime.get', 'ManualEntryController@overtimeGet');
    $router->post('api/manual-overtime.save', 'ManualEntryController@overtimeSave');
    $router->post('api/manual-overtime.delete', 'ManualEntryController@overtimeDelete');
    $router->post('api/ot-rate.scope-options', 'SetupRulesController@otScopeOptions');
    $router->post('api/ot-rate.options', 'MasterController@getMaster');
    $router->post('api/leave-type.options', 'MasterController@getMaster');
    $router->get('api/ot-rate.list', 'SetupRulesController@otRateList');
    $router->get('api/ot-rate.get', 'SetupRulesController@otRateGet');
    $router->post('api/ot-rate.save', 'SetupRulesController@otRateSave');
    $router->post('api/ot-rate.delete', 'SetupRulesController@otRateDelete');
    $router->post('api/ot-rate.toggle-status', 'SetupRulesController@otRateToggleStatus');
    $router->get('api/holiday.list', 'SetupRulesController@holidayList');
    $router->get('api/holiday.get', 'SetupRulesController@holidayGet');
    $router->post('api/holiday.save', 'SetupRulesController@holidaySave');
    $router->post('api/holiday.delete', 'SetupRulesController@holidayDelete');
    $router->post('api/holiday.toggle-status', 'SetupRulesController@holidayToggleStatus');
    $router->post('api/shift.options', 'MasterController@getMaster');
    $router->get('reports', 'ReportsController@index');
    $router->get('api/report.list', 'ReportsController@list');
    $router->get('api/report.generate', 'ReportsController@generate');
    $router->get('api/report.export-logs', 'ReportsController@exportLogs');
    $router->get('submission', 'SubmissionController@index');
    $router->post('api/employee.list', 'EmployeeController@list');
    $router->get('/employees/create', 'EmployeeController@create');
    $router->get('/employees/{id}', 'EmployeeController@detail');
    $router->get('api/address/search', 'AddressController@getMetadata');
    $router->post('api/company.get', 'CompanyProfileController@get');
    $router->post('api/company.save', 'CompanyProfileController@save');
    $router->post('api/country.get', 'MasterController@getMaster');
    $router->post('api/nationality.get', 'MasterController@getMaster');
    $router->post('api/religion.get', 'MasterController@getMaster');
    $router->post('api/structure.role', 'CompanyProfileController@role');
    $router->post('api/structure.branch', 'CompanyProfileController@branch');
    $router->post('api/structure.department', 'CompanyProfileController@department');
    $router->post('api/structure.position', 'CompanyProfileController@position');
    $router->post('api/structure.rank', 'CompanyProfileController@rank');
    $router->post('api/structure.branch.save', 'CompanyProfileController@branchSave');
    $router->post('api/structure.branch.delete', 'CompanyProfileController@branchDelete');
    $router->post('api/structure.role.save', 'CompanyProfileController@roleSave');
    $router->post('api/structure.role.delete', 'CompanyProfileController@roleDelete');
    $router->post('api/structure.department.save', 'CompanyProfileController@departmentSave');
    $router->post('api/structure.department.delete', 'CompanyProfileController@departmentDelete');
    $router->post('api/structure.position.save', 'CompanyProfileController@positionSave');
    $router->post('api/structure.position.delete', 'CompanyProfileController@positionDelete');
    $router->post('api/structure.rank.save', 'CompanyProfileController@rankSave');
    $router->post('api/structure.rank.delete', 'CompanyProfileController@rankDelete');
    $router->post('api/bank.get', 'MasterController@getMaster');
    $router->post('api/department.get', 'MasterController@getMaster');
    $router->post('api/role.get', 'MasterController@getMaster');
    $router->post('api/position.get', 'MasterController@getMaster');
    $router->post('api/branch.get', 'MasterController@getMaster');
    $router->post('api/employee.report_to.get', 'EmployeeController@reportToOptions');
    $router->post('api/bank_account.list', 'BankAccountController@list');
    $router->post('api/bank_account.save', 'BankAccountController@save');
    $router->post('api/bank_account.delete', 'BankAccountController@delete');
    $router->get('api/employee.get', 'EmployeeController@get');
    $router->post('api/employee.save', 'EmployeeController@save');
    $router->post('api/employee.delete', 'EmployeeController@delete');
    $router->get('api/employee.dependent.list', 'EmployeeController@dependentList');
    $router->post('api/employee.dependent.save', 'EmployeeController@dependentSave');
    $router->post('api/employee.dependent.delete', 'EmployeeController@dependentDelete');
    $router->get('api/employee.parent.list', 'EmployeeController@parentList');
    $router->post('api/employee.parent.save', 'EmployeeController@parentSave');
    $router->post('api/employee.parent.delete', 'EmployeeController@parentDelete');
    $router->post('api/employee.earning-deduction.options', 'EmployeeController@earningDeductionOptions');
    $router->get('api/employee.earning-deduction.list', 'EmployeeController@earningDeductionList');
    $router->get('api/employee.earning-deduction.get', 'EmployeeController@earningDeductionGet');
    $router->post('api/employee.earning-deduction.save', 'EmployeeController@earningDeductionSave');
    $router->post('api/employee.earning-deduction.status', 'EmployeeController@earningDeductionStatus');
    $router->post('api/employee.earning-deduction.delete', 'EmployeeController@earningDeductionDelete');
    $router->get('api/employee.document.list', 'EmployeeController@documentList');
    $router->post('api/employee.document.upload', 'EmployeeController@documentUpload');
    $router->get('api/employee.document.view', 'EmployeeController@documentView');
    $router->post('api/employee.document.delete', 'EmployeeController@documentDelete');
    $router->dispatch();