-- 2026-08-30, explicit request: "ในตารางประเทศตอนนี้มีให้เลือกทุกประเทศไหมครับที่ ที่เอามาเลือกในประเทศที่จด
-- ทะเบียน ถ้าไม่ครบให้ใส่ข้อมูลไปให้ครบครับ" -- master_countries only had the 4 countries this app's
-- own statutory calculation engine actually supports (TH/SG/MY/US). Confirmed via AskUserQuestion:
-- the user wants the FULL world list added regardless (~190 more countries selectable as a
-- company's registered country), understanding that only TH/SG/MY/US have real tax/SSO calculation
-- behind them today -- a company registering under any other country is a valid real-world case
-- this app just doesn't compute statutory items for yet (same "config exists, no consumer yet"
-- precedent as several other features documented in this project's own history).
-- ON DUPLICATE KEY UPDATE (keyed on the existing UNIQUE `code` constraint) so this is safe to
-- re-run and never overwrites the 4 existing rows' own currency/name data with a duplicate insert
-- attempt -- it just updates them to the same values, a no-op in practice.
INSERT INTO `master_countries` (`countries_code`, `countries_name_th`, `countries_name_en`, `currency_code`, `is_active`, `created_at`, `created_by`, `updated_at`, `updated_by`) VALUES
-- Asia
('AF', 'อัฟกานิสถาน', 'Afghanistan', 'AFN', 'active', NOW(), 1, NOW(), 1),
('AM', 'อาร์เมเนีย', 'Armenia', 'AMD', 'active', NOW(), 1, NOW(), 1),
('AZ', 'อาเซอร์ไบจาน', 'Azerbaijan', 'AZN', 'active', NOW(), 1, NOW(), 1),
('BH', 'บาห์เรน', 'Bahrain', 'BHD', 'active', NOW(), 1, NOW(), 1),
('BD', 'บังกลาเทศ', 'Bangladesh', 'BDT', 'active', NOW(), 1, NOW(), 1),
('BT', 'ภูฏาน', 'Bhutan', 'BTN', 'active', NOW(), 1, NOW(), 1),
('BN', 'บรูไน', 'Brunei', 'BND', 'active', NOW(), 1, NOW(), 1),
('KH', 'กัมพูชา', 'Cambodia', 'KHR', 'active', NOW(), 1, NOW(), 1),
('CN', 'จีน', 'China', 'CNY', 'active', NOW(), 1, NOW(), 1),
('CY', 'ไซปรัส', 'Cyprus', 'EUR', 'active', NOW(), 1, NOW(), 1),
('GE', 'จอร์เจีย', 'Georgia', 'GEL', 'active', NOW(), 1, NOW(), 1),
('HK', 'ฮ่องกง', 'Hong Kong', 'HKD', 'active', NOW(), 1, NOW(), 1),
('IN', 'อินเดีย', 'India', 'INR', 'active', NOW(), 1, NOW(), 1),
('ID', 'อินโดนีเซีย', 'Indonesia', 'IDR', 'active', NOW(), 1, NOW(), 1),
('IR', 'อิหร่าน', 'Iran', 'IRR', 'active', NOW(), 1, NOW(), 1),
('IQ', 'อิรัก', 'Iraq', 'IQD', 'active', NOW(), 1, NOW(), 1),
('IL', 'อิสราเอล', 'Israel', 'ILS', 'active', NOW(), 1, NOW(), 1),
('JP', 'ญี่ปุ่น', 'Japan', 'JPY', 'active', NOW(), 1, NOW(), 1),
('JO', 'จอร์แดน', 'Jordan', 'JOD', 'active', NOW(), 1, NOW(), 1),
('KZ', 'คาซัคสถาน', 'Kazakhstan', 'KZT', 'active', NOW(), 1, NOW(), 1),
('KW', 'คูเวต', 'Kuwait', 'KWD', 'active', NOW(), 1, NOW(), 1),
('KG', 'คีร์กีซสถาน', 'Kyrgyzstan', 'KGS', 'active', NOW(), 1, NOW(), 1),
('LA', 'ลาว', 'Laos', 'LAK', 'active', NOW(), 1, NOW(), 1),
('LB', 'เลบานอน', 'Lebanon', 'LBP', 'active', NOW(), 1, NOW(), 1),
('MO', 'มาเก๊า', 'Macau', 'MOP', 'active', NOW(), 1, NOW(), 1),
('MV', 'มัลดีฟส์', 'Maldives', 'MVR', 'active', NOW(), 1, NOW(), 1),
('MN', 'มองโกเลีย', 'Mongolia', 'MNT', 'active', NOW(), 1, NOW(), 1),
('MM', 'เมียนมา', 'Myanmar', 'MMK', 'active', NOW(), 1, NOW(), 1),
('NP', 'เนปาล', 'Nepal', 'NPR', 'active', NOW(), 1, NOW(), 1),
('KP', 'เกาหลีเหนือ', 'North Korea', 'KPW', 'active', NOW(), 1, NOW(), 1),
('OM', 'โอมาน', 'Oman', 'OMR', 'active', NOW(), 1, NOW(), 1),
('PK', 'ปากีสถาน', 'Pakistan', 'PKR', 'active', NOW(), 1, NOW(), 1),
('PS', 'ปาเลสไตน์', 'Palestine', 'ILS', 'active', NOW(), 1, NOW(), 1),
('PH', 'ฟิลิปปินส์', 'Philippines', 'PHP', 'active', NOW(), 1, NOW(), 1),
('QA', 'กาตาร์', 'Qatar', 'QAR', 'active', NOW(), 1, NOW(), 1),
('SA', 'ซาอุดีอาระเบีย', 'Saudi Arabia', 'SAR', 'active', NOW(), 1, NOW(), 1),
('KR', 'เกาหลีใต้', 'South Korea', 'KRW', 'active', NOW(), 1, NOW(), 1),
('LK', 'ศรีลังกา', 'Sri Lanka', 'LKR', 'active', NOW(), 1, NOW(), 1),
('SY', 'ซีเรีย', 'Syria', 'SYP', 'active', NOW(), 1, NOW(), 1),
('TW', 'ไต้หวัน', 'Taiwan', 'TWD', 'active', NOW(), 1, NOW(), 1),
('TJ', 'ทาจิกิสถาน', 'Tajikistan', 'TJS', 'active', NOW(), 1, NOW(), 1),
('TL', 'ติมอร์-เลสเต', 'Timor-Leste', 'USD', 'active', NOW(), 1, NOW(), 1),
('TR', 'ตุรกี', 'Turkey', 'TRY', 'active', NOW(), 1, NOW(), 1),
('TM', 'เติร์กเมนิสถาน', 'Turkmenistan', 'TMT', 'active', NOW(), 1, NOW(), 1),
('AE', 'สหรัฐอาหรับเอมิเรตส์', 'United Arab Emirates', 'AED', 'active', NOW(), 1, NOW(), 1),
('UZ', 'อุซเบกิสถาน', 'Uzbekistan', 'UZS', 'active', NOW(), 1, NOW(), 1),
('VN', 'เวียดนาม', 'Vietnam', 'VND', 'active', NOW(), 1, NOW(), 1),
('YE', 'เยเมน', 'Yemen', 'YER', 'active', NOW(), 1, NOW(), 1),
-- Europe
('AL', 'แอลเบเนีย', 'Albania', 'ALL', 'active', NOW(), 1, NOW(), 1),
('AD', 'อันดอร์รา', 'Andorra', 'EUR', 'active', NOW(), 1, NOW(), 1),
('AT', 'ออสเตรีย', 'Austria', 'EUR', 'active', NOW(), 1, NOW(), 1),
('BY', 'เบลารุส', 'Belarus', 'BYN', 'active', NOW(), 1, NOW(), 1),
('BE', 'เบลเยียม', 'Belgium', 'EUR', 'active', NOW(), 1, NOW(), 1),
('BA', 'บอสเนียและเฮอร์เซโกวีนา', 'Bosnia and Herzegovina', 'BAM', 'active', NOW(), 1, NOW(), 1),
('BG', 'บัลแกเรีย', 'Bulgaria', 'BGN', 'active', NOW(), 1, NOW(), 1),
('HR', 'โครเอเชีย', 'Croatia', 'EUR', 'active', NOW(), 1, NOW(), 1),
('CZ', 'เช็กเกีย', 'Czech Republic', 'CZK', 'active', NOW(), 1, NOW(), 1),
('DK', 'เดนมาร์ก', 'Denmark', 'DKK', 'active', NOW(), 1, NOW(), 1),
('EE', 'เอสโตเนีย', 'Estonia', 'EUR', 'active', NOW(), 1, NOW(), 1),
('FI', 'ฟินแลนด์', 'Finland', 'EUR', 'active', NOW(), 1, NOW(), 1),
('FR', 'ฝรั่งเศส', 'France', 'EUR', 'active', NOW(), 1, NOW(), 1),
('DE', 'เยอรมนี', 'Germany', 'EUR', 'active', NOW(), 1, NOW(), 1),
('GR', 'กรีซ', 'Greece', 'EUR', 'active', NOW(), 1, NOW(), 1),
('HU', 'ฮังการี', 'Hungary', 'HUF', 'active', NOW(), 1, NOW(), 1),
('IS', 'ไอซ์แลนด์', 'Iceland', 'ISK', 'active', NOW(), 1, NOW(), 1),
('IE', 'ไอร์แลนด์', 'Ireland', 'EUR', 'active', NOW(), 1, NOW(), 1),
('IT', 'อิตาลี', 'Italy', 'EUR', 'active', NOW(), 1, NOW(), 1),
('XK', 'โคโซโว', 'Kosovo', 'EUR', 'active', NOW(), 1, NOW(), 1),
('LV', 'ลัตเวีย', 'Latvia', 'EUR', 'active', NOW(), 1, NOW(), 1),
('LI', 'ลิกเตนสไตน์', 'Liechtenstein', 'CHF', 'active', NOW(), 1, NOW(), 1),
('LT', 'ลิทัวเนีย', 'Lithuania', 'EUR', 'active', NOW(), 1, NOW(), 1),
('LU', 'ลักเซมเบิร์ก', 'Luxembourg', 'EUR', 'active', NOW(), 1, NOW(), 1),
('MT', 'มอลตา', 'Malta', 'EUR', 'active', NOW(), 1, NOW(), 1),
('MD', 'มอลโดวา', 'Moldova', 'MDL', 'active', NOW(), 1, NOW(), 1),
('MC', 'โมนาโก', 'Monaco', 'EUR', 'active', NOW(), 1, NOW(), 1),
('ME', 'มอนเตเนโกร', 'Montenegro', 'EUR', 'active', NOW(), 1, NOW(), 1),
('NL', 'เนเธอร์แลนด์', 'Netherlands', 'EUR', 'active', NOW(), 1, NOW(), 1),
('MK', 'นอร์ทมาซิโดเนีย', 'North Macedonia', 'MKD', 'active', NOW(), 1, NOW(), 1),
('NO', 'นอร์เวย์', 'Norway', 'NOK', 'active', NOW(), 1, NOW(), 1),
('PL', 'โปแลนด์', 'Poland', 'PLN', 'active', NOW(), 1, NOW(), 1),
('PT', 'โปรตุเกส', 'Portugal', 'EUR', 'active', NOW(), 1, NOW(), 1),
('RO', 'โรมาเนีย', 'Romania', 'RON', 'active', NOW(), 1, NOW(), 1),
('RU', 'รัสเซีย', 'Russia', 'RUB', 'active', NOW(), 1, NOW(), 1),
('SM', 'ซานมารีโน', 'San Marino', 'EUR', 'active', NOW(), 1, NOW(), 1),
('RS', 'เซอร์เบีย', 'Serbia', 'RSD', 'active', NOW(), 1, NOW(), 1),
('SK', 'สโลวาเกีย', 'Slovakia', 'EUR', 'active', NOW(), 1, NOW(), 1),
('SI', 'สโลวีเนีย', 'Slovenia', 'EUR', 'active', NOW(), 1, NOW(), 1),
('ES', 'สเปน', 'Spain', 'EUR', 'active', NOW(), 1, NOW(), 1),
('SE', 'สวีเดน', 'Sweden', 'SEK', 'active', NOW(), 1, NOW(), 1),
('CH', 'สวิตเซอร์แลนด์', 'Switzerland', 'CHF', 'active', NOW(), 1, NOW(), 1),
('UA', 'ยูเครน', 'Ukraine', 'UAH', 'active', NOW(), 1, NOW(), 1),
('GB', 'สหราชอาณาจักร', 'United Kingdom', 'GBP', 'active', NOW(), 1, NOW(), 1),
('VA', 'นครรัฐวาติกัน', 'Vatican City', 'EUR', 'active', NOW(), 1, NOW(), 1),
-- Africa
('DZ', 'แอลจีเรีย', 'Algeria', 'DZD', 'active', NOW(), 1, NOW(), 1),
('AO', 'แองโกลา', 'Angola', 'AOA', 'active', NOW(), 1, NOW(), 1),
('BJ', 'เบนิน', 'Benin', 'XOF', 'active', NOW(), 1, NOW(), 1),
('BW', 'บอตสวานา', 'Botswana', 'BWP', 'active', NOW(), 1, NOW(), 1),
('BF', 'บูร์กินาฟาโซ', 'Burkina Faso', 'XOF', 'active', NOW(), 1, NOW(), 1),
('BI', 'บุรุนดี', 'Burundi', 'BIF', 'active', NOW(), 1, NOW(), 1),
('CM', 'แคเมอรูน', 'Cameroon', 'XAF', 'active', NOW(), 1, NOW(), 1),
('CV', 'กาบูเวร์ดี', 'Cape Verde', 'CVE', 'active', NOW(), 1, NOW(), 1),
('CF', 'สาธารณรัฐแอฟริกากลาง', 'Central African Republic', 'XAF', 'active', NOW(), 1, NOW(), 1),
('TD', 'ชาด', 'Chad', 'XAF', 'active', NOW(), 1, NOW(), 1),
('KM', 'คอโมโรส', 'Comoros', 'KMF', 'active', NOW(), 1, NOW(), 1),
('CG', 'คองโก', 'Congo (Republic)', 'XAF', 'active', NOW(), 1, NOW(), 1),
('CD', 'สาธารณรัฐประชาธิปไตยคองโก', 'Congo (DRC)', 'CDF', 'active', NOW(), 1, NOW(), 1),
('CI', 'โกตดิวัวร์', "Cote d'Ivoire", 'XOF', 'active', NOW(), 1, NOW(), 1),
('DJ', 'จิบูตี', 'Djibouti', 'DJF', 'active', NOW(), 1, NOW(), 1),
('EG', 'อียิปต์', 'Egypt', 'EGP', 'active', NOW(), 1, NOW(), 1),
('GQ', 'อิเควทอเรียลกินี', 'Equatorial Guinea', 'XAF', 'active', NOW(), 1, NOW(), 1),
('ER', 'เอริเทรีย', 'Eritrea', 'ERN', 'active', NOW(), 1, NOW(), 1),
('SZ', 'เอสวาตินี', 'Eswatini', 'SZL', 'active', NOW(), 1, NOW(), 1),
('ET', 'เอธิโอเปีย', 'Ethiopia', 'ETB', 'active', NOW(), 1, NOW(), 1),
('GA', 'กาบอง', 'Gabon', 'XAF', 'active', NOW(), 1, NOW(), 1),
('GM', 'แกมเบีย', 'Gambia', 'GMD', 'active', NOW(), 1, NOW(), 1),
('GH', 'กานา', 'Ghana', 'GHS', 'active', NOW(), 1, NOW(), 1),
('GN', 'กินี', 'Guinea', 'GNF', 'active', NOW(), 1, NOW(), 1),
('GW', 'กินี-บิสเซา', 'Guinea-Bissau', 'XOF', 'active', NOW(), 1, NOW(), 1),
('KE', 'เคนยา', 'Kenya', 'KES', 'active', NOW(), 1, NOW(), 1),
('LS', 'เลโซโท', 'Lesotho', 'LSL', 'active', NOW(), 1, NOW(), 1),
('LR', 'ไลบีเรีย', 'Liberia', 'LRD', 'active', NOW(), 1, NOW(), 1),
('LY', 'ลิเบีย', 'Libya', 'LYD', 'active', NOW(), 1, NOW(), 1),
('MG', 'มาดากัสการ์', 'Madagascar', 'MGA', 'active', NOW(), 1, NOW(), 1),
('MW', 'มาลาวี', 'Malawi', 'MWK', 'active', NOW(), 1, NOW(), 1),
('ML', 'มาลี', 'Mali', 'XOF', 'active', NOW(), 1, NOW(), 1),
('MR', 'มอริเตเนีย', 'Mauritania', 'MRU', 'active', NOW(), 1, NOW(), 1),
('MU', 'มอริเชียส', 'Mauritius', 'MUR', 'active', NOW(), 1, NOW(), 1),
('MA', 'โมร็อกโก', 'Morocco', 'MAD', 'active', NOW(), 1, NOW(), 1),
('MZ', 'โมซัมบิก', 'Mozambique', 'MZN', 'active', NOW(), 1, NOW(), 1),
('NA', 'นามิเบีย', 'Namibia', 'NAD', 'active', NOW(), 1, NOW(), 1),
('NE', 'ไนเจอร์', 'Niger', 'XOF', 'active', NOW(), 1, NOW(), 1),
('NG', 'ไนจีเรีย', 'Nigeria', 'NGN', 'active', NOW(), 1, NOW(), 1),
('RW', 'รวันดา', 'Rwanda', 'RWF', 'active', NOW(), 1, NOW(), 1),
('ST', 'เซาตูเมและปรินซิปี', 'Sao Tome and Principe', 'STN', 'active', NOW(), 1, NOW(), 1),
('SN', 'เซเนกัล', 'Senegal', 'XOF', 'active', NOW(), 1, NOW(), 1),
('SC', 'เซเชลส์', 'Seychelles', 'SCR', 'active', NOW(), 1, NOW(), 1),
('SL', 'เซียร์ราลีโอน', 'Sierra Leone', 'SLE', 'active', NOW(), 1, NOW(), 1),
('SO', 'โซมาเลีย', 'Somalia', 'SOS', 'active', NOW(), 1, NOW(), 1),
('ZA', 'แอฟริกาใต้', 'South Africa', 'ZAR', 'active', NOW(), 1, NOW(), 1),
('SS', 'เซาท์ซูดาน', 'South Sudan', 'SSP', 'active', NOW(), 1, NOW(), 1),
('SD', 'ซูดาน', 'Sudan', 'SDG', 'active', NOW(), 1, NOW(), 1),
('TZ', 'แทนซาเนีย', 'Tanzania', 'TZS', 'active', NOW(), 1, NOW(), 1),
('TG', 'โตโก', 'Togo', 'XOF', 'active', NOW(), 1, NOW(), 1),
('TN', 'ตูนิเซีย', 'Tunisia', 'TND', 'active', NOW(), 1, NOW(), 1),
('UG', 'ยูกันดา', 'Uganda', 'UGX', 'active', NOW(), 1, NOW(), 1),
('ZM', 'แซมเบีย', 'Zambia', 'ZMW', 'active', NOW(), 1, NOW(), 1),
('ZW', 'ซิมบับเว', 'Zimbabwe', 'ZWL', 'active', NOW(), 1, NOW(), 1),
-- Americas
('AG', 'แอนติกาและบาร์บูดา', 'Antigua and Barbuda', 'XCD', 'active', NOW(), 1, NOW(), 1),
('AR', 'อาร์เจนตินา', 'Argentina', 'ARS', 'active', NOW(), 1, NOW(), 1),
('BS', 'บาฮามาส', 'Bahamas', 'BSD', 'active', NOW(), 1, NOW(), 1),
('BB', 'บาร์เบโดส', 'Barbados', 'BBD', 'active', NOW(), 1, NOW(), 1),
('BZ', 'เบลีซ', 'Belize', 'BZD', 'active', NOW(), 1, NOW(), 1),
('BO', 'โบลิเวีย', 'Bolivia', 'BOB', 'active', NOW(), 1, NOW(), 1),
('BR', 'บราซิล', 'Brazil', 'BRL', 'active', NOW(), 1, NOW(), 1),
('CA', 'แคนาดา', 'Canada', 'CAD', 'active', NOW(), 1, NOW(), 1),
('CL', 'ชิลี', 'Chile', 'CLP', 'active', NOW(), 1, NOW(), 1),
('CO', 'โคลอมเบีย', 'Colombia', 'COP', 'active', NOW(), 1, NOW(), 1),
('CR', 'คอสตาริกา', 'Costa Rica', 'CRC', 'active', NOW(), 1, NOW(), 1),
('CU', 'คิวบา', 'Cuba', 'CUP', 'active', NOW(), 1, NOW(), 1),
('DM', 'โดมินิกา', 'Dominica', 'XCD', 'active', NOW(), 1, NOW(), 1),
('DO', 'สาธารณรัฐโดมินิกัน', 'Dominican Republic', 'DOP', 'active', NOW(), 1, NOW(), 1),
('EC', 'เอกวาดอร์', 'Ecuador', 'USD', 'active', NOW(), 1, NOW(), 1),
('SV', 'เอลซัลวาดอร์', 'El Salvador', 'USD', 'active', NOW(), 1, NOW(), 1),
('GD', 'เกรเนดา', 'Grenada', 'XCD', 'active', NOW(), 1, NOW(), 1),
('GT', 'กัวเตมาลา', 'Guatemala', 'GTQ', 'active', NOW(), 1, NOW(), 1),
('GY', 'กายอานา', 'Guyana', 'GYD', 'active', NOW(), 1, NOW(), 1),
('HT', 'เฮติ', 'Haiti', 'HTG', 'active', NOW(), 1, NOW(), 1),
('HN', 'ฮอนดูรัส', 'Honduras', 'HNL', 'active', NOW(), 1, NOW(), 1),
('JM', 'จาเมกา', 'Jamaica', 'JMD', 'active', NOW(), 1, NOW(), 1),
('MX', 'เม็กซิโก', 'Mexico', 'MXN', 'active', NOW(), 1, NOW(), 1),
('NI', 'นิการากัว', 'Nicaragua', 'NIO', 'active', NOW(), 1, NOW(), 1),
('PA', 'ปานามา', 'Panama', 'PAB', 'active', NOW(), 1, NOW(), 1),
('PY', 'ปารากวัย', 'Paraguay', 'PYG', 'active', NOW(), 1, NOW(), 1),
('PE', 'เปรู', 'Peru', 'PEN', 'active', NOW(), 1, NOW(), 1),
('KN', 'เซนต์คิตส์และเนวิส', 'Saint Kitts and Nevis', 'XCD', 'active', NOW(), 1, NOW(), 1),
('LC', 'เซนต์ลูเซีย', 'Saint Lucia', 'XCD', 'active', NOW(), 1, NOW(), 1),
('VC', 'เซนต์วินเซนต์และเกรนาดีนส์', 'Saint Vincent and the Grenadines', 'XCD', 'active', NOW(), 1, NOW(), 1),
('SR', 'ซูรินาม', 'Suriname', 'SRD', 'active', NOW(), 1, NOW(), 1),
('TT', 'ตรินิแดดและโตเบโก', 'Trinidad and Tobago', 'TTD', 'active', NOW(), 1, NOW(), 1),
('UY', 'อุรุกวัย', 'Uruguay', 'UYU', 'active', NOW(), 1, NOW(), 1),
('VE', 'เวเนซุเอลา', 'Venezuela', 'VES', 'active', NOW(), 1, NOW(), 1),
-- Oceania
('AU', 'ออสเตรเลีย', 'Australia', 'AUD', 'active', NOW(), 1, NOW(), 1),
('FJ', 'ฟิจิ', 'Fiji', 'FJD', 'active', NOW(), 1, NOW(), 1),
('KI', 'คิริบาส', 'Kiribati', 'AUD', 'active', NOW(), 1, NOW(), 1),
('MH', 'หมู่เกาะมาร์แชลล์', 'Marshall Islands', 'USD', 'active', NOW(), 1, NOW(), 1),
('FM', 'ไมโครนีเซีย', 'Micronesia', 'USD', 'active', NOW(), 1, NOW(), 1),
('NR', 'นาอูรู', 'Nauru', 'AUD', 'active', NOW(), 1, NOW(), 1),
('NZ', 'นิวซีแลนด์', 'New Zealand', 'NZD', 'active', NOW(), 1, NOW(), 1),
('PW', 'ปาเลา', 'Palau', 'USD', 'active', NOW(), 1, NOW(), 1),
('PG', 'ปาปัวนิวกินี', 'Papua New Guinea', 'PGK', 'active', NOW(), 1, NOW(), 1),
('WS', 'ซามัว', 'Samoa', 'WST', 'active', NOW(), 1, NOW(), 1),
('SB', 'หมู่เกาะโซโลมอน', 'Solomon Islands', 'SBD', 'active', NOW(), 1, NOW(), 1),
('TO', 'ตองกา', 'Tonga', 'TOP', 'active', NOW(), 1, NOW(), 1),
('TV', 'ตูวาลู', 'Tuvalu', 'AUD', 'active', NOW(), 1, NOW(), 1),
('VU', 'วานูอาตู', 'Vanuatu', 'VUV', 'active', NOW(), 1, NOW(), 1)
ON DUPLICATE KEY UPDATE
    `countries_name_th` = VALUES(`countries_name_th`),
    `countries_name_en` = VALUES(`countries_name_en`),
    `currency_code` = VALUES(`currency_code`),
    `updated_at` = NOW(),
    `updated_by` = VALUES(`created_by`);
